### ISSUE TITLE
Use forward slashes so it builds on linux

### ISSUE THREAD

**Issue by pavpanchekha** [herbie-fp/avx-herbie#1]
On this line, please use a forward slash instead of a backwards slash. Forward slashes work everywhere, backslashes only Windows.

https://github.com/herbie-fp/avx-herbie/blob/02998e2d4a434bdebfbfd2fd96b2295f3b19d7bb/install.rkt#L24

**Comment by JonasRegehr** [comment]
Sorry just saw this. It should be changed now.
